var TRANSLATIONS = [
    ["I try", "προσπαθώ", ["verb"]],
    ["I bring", "φέρνω", ["verb"]],
    ["I go", "φεύγω", ["verb"]],
    ["I send", "στέλνω", ["verb"]],
    ["I wash", "πλένω", ["verb"]],
    ["I fall", "πέφτω", ["verb"]],
    ["I die", "πεθαίνω", ["verb"]],
    ["I take", "παίρνω", ["verb"]],
    ["I give", "δίνω", ["verb"]],
    ["I live", "ζω", ["verb"]],
    ["first (m)", "πρώτος", ["ordinal"]],
    ["second (m)", "δεύτερος", ["ordinal"]],
    ["third (m)", "τρίτος", ["ordinal"]],
    ["fourth (m)", "τέταρτος", ["ordinal"]],
    ["fifth (m)", "πέμπτος", ["ordinal"]],
    ["sixth (m)", "έκτος", ["ordinal"]],
    ["seventh (m)", "έβδομος", ["ordinal"]],
    ["eighth (m)", "όγδοος", ["ordinal"]],
    ["eighth (m)", "όγδοη", ["ordinal"]],
    ["eighth (m)", "όγδοο", ["ordinal"]],
    ["ninth (m)", "ένατος", ["ordinal"]],
    ["tenth (m)", "δέκατος", ["ordinal"]],
    ["eleventh (m)", "ενδέκατος", ["ordinal"]],
    ["twelfth (m)", "δωδέκατος", ["ordinal"]],
    ["thirteenth (m)", "δέκατος τρίτος", ["ordinal"]],
    ["fourteenth (m)", "δέκατος τέταρτος", ["ordinal"]],
    ["fifteenth (m)", "δέκατος πέμπτος", ["ordinal"]],
    ["sixteenth (m)", "δέκατος έκτος", ["ordinal"]],
    ["seventeenth (m)", "δέκατοσ έβδομος", ["ordinal"]],
    ["eighteenth (m)", "δέκατος όγδοος", ["ordinal"]],
    ["nineteenth (m)", "δέκατος ένατος", ["ordinal"]],
    ["twentieth (m)", "εικοστός", ["ordinal"]],
];
