var TRANSLATIONS = [
    ["I try", "προσπαθώ", ["verb"]],
    ["I bring", "φέρνω", ["verb"]],
    ["I go", "φεύγω", ["verb"]],
    ["I send", "στέλνω", ["verb"]],
    ["I wash", "πλένω", ["verb"]],
    ["I fall", "πέφτω", ["verb"]],
    ["I die", "πεθαίνω", ["verb"]],
    ["I take", "παίρνω", ["verb"]],
    ["I give", "δίνω", ["verb"]],
    ["I live", "ζω", ["verb"]],
    ["first (m)", "πρώτος", ["ordinal"]],
    ["first (f)", "πρώτη", ["ordinal"]],
    ["first (n)", "πρώτο", ["ordinal"]],
    ["second (m)", "δεύτερος", ["ordinal"]],
    ["second (f)", "δεύτερη", ["ordinal"]],
    ["second (n)", "δεύτερο", ["ordinal"]],
    ["third (m)", "τρίτος", ["ordinal"]],
    ["third (f)", "τρίτη", ["ordinal"]],
    ["third (n)", "τρίτο", ["ordinal"]],
    ["fourth (m)", "τέταρτος", ["ordinal"]],
    ["fourth (f)", "τέταρτη", ["ordinal"]],
    ["fourth (n)", "τέταρτο", ["ordinal"]],
    ["fifth (m)", "πέμπτος", ["ordinal"]],
    ["fifth (f)", "πέμπτη", ["ordinal"]],
    ["fifth (n)", "πέμπτο", ["ordinal"]],
    ["sixth (m)", "έκτος", ["ordinal"]],
    ["sixth (f)", "έκτη", ["ordinal"]],
    ["sixth (n)", "έκτο", ["ordinal"]],
    ["seventh (m)", "έβδομος", ["ordinal"]],
    ["seventh (f)", "έβδομη", ["ordinal"]],
    ["seventh (n)", "έβδομο", ["ordinal"]],
    ["eighth (m)", "όγδοος", ["ordinal"]],
    ["eighth (m)", "όγδοη", ["ordinal"]],
    ["eighth (m)", "όγδοο", ["ordinal"]],
    ["ninth (m)", "ένατος", ["ordinal"]],
    ["ninth (f)", "ένατη", ["ordinal"]],
    ["ninth (n)", "ένατο", ["ordinal"]],
    ["tenth (m)", "δέκατος", ["ordinal"]],
    ["tenth (f)", "δέκατη", ["ordinal"]],
    ["tenth (n)", "δέκατο", ["ordinal"]],
    ["eleventh (m)", "ενδέκατος", ["ordinal"]],
    ["eleventh (f)", "ενδέκατη", ["ordinal"]],
    ["eleventh (n)", "ενδέκατο", ["ordinal"]],
    ["twelfth (m)", "δωδέκατος", ["ordinal"]],
    ["twelfth (f)", "δωδέκατη", ["ordinal"]],
    ["twelfth (n)", "δωδέκατο", ["ordinal"]],
    ["thirteenth (m)", "δέκατος τρίτος", ["ordinal"]],
    ["fourteenth (m)", "δέκατος τέταρτος", ["ordinal"]],
    ["fifteenth (m)", "δέκατος πέμπτος", ["ordinal"]],
    ["sixteenth (m)", "δέκατος έκτος", ["ordinal"]],
    ["seventeenth (m)", "δέκατοσ έβδομος", ["ordinal"]],
    ["eighteenth (m)", "δέκατος όγδοος", ["ordinal"]],
    ["nineteenth (m)", "δέκατος ένατος", ["ordinal"]],
    ["twentieth (m)", "εικοστός", ["ordinal"]],
];
