var TRANSLATIONS = [
    ["I try", "προσπαθώ"],
    ["I bring", "φέρνω"],
    ["I go", "φεύγω"],
    ["I send", "στέλνω"],
    ["I wash", "πλένω"],
    ["I fall", "πέφτω"],
    ["I die", "πεθαίνω"],
    ["I take", "παίρνω"],
    ["I give", "δίνω"],
    ["I live", "ζω"],
    ["first (m)", "πρώτος"],
    ["first (f)", "πρώτη"],
    ["first (n)", "πρώτο"],
    ["second (m)", "δεύτερος"],
    ["second (f)", "δεύτερη"],
    ["second (n)", "δεύτερο"],
    ["third (m)", "τρίτος"],
    ["third (f)", "τρίτη"],
    ["third (n)", "τρίτο"],
    ["fourth (m)", "τέταρτος"],
    ["fourth (f)", "τέταρτη"],
    ["fourth (n)", "τέταρτο"],
    ["fifth (m)", "πέμπτος"],
    ["fifth (f)", "πέμπτη"],
    ["fifth (n)", "πέμπτο"],
    ["sixth (m)", "έκτος"],
    ["sixth (f)", "έκτη"],
    ["sixth (n)", "έκτο"],
    ["seventh (m)", "έβδομος"],
    ["seventh (f)", "έβδομη"],
    ["seventh (n)", "έβδομο"],
    ["eighth (m)", "όγδοος"],
    ["eighth (m)", "όγδοη"],
    ["eighth (m)", "όγδοο"],
    ["ninth (m)", "ένατος"],
    ["ninth (f)", "ένατη"],
    ["ninth (n)", "ένατο"],
    ["tenth (m)", "δέκατος"],
    ["tenth (f)", "δέκατη"],
    ["tenth (n)", "δέκατο"],
    ["eleventh (m)", "ενδέκατος"],
    ["eleventh (f)", "ενδέκατη"],
    ["eleventh (n)", "ενδέκατο"],
    ["twelfth (m)", "δωδέκατος"],
    ["twelfth (f)", "δωδέκατη"],
    ["twelfth (n)", "δωδέκατο"],
    ["thirteenth (m)", "δέκατος τρίτος"],
    ["fourteenth (m)", "δέκατος τέταρτος"],
    ["fifteenth (m)", "δέκατος πέμπτος"],
    ["sixteenth (m)", "δέκατος έκτος"],
    ["seventeenth (m)", "δέκατοσ έβδομος"],
    ["eighteenth (m)", "δέκατος όγδοος"],
    ["nineteenth (m)", "δέκατος ένατος"],
    ["twentieth (m)", "εικοστός"],
];
